---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kjm24-test-redis-pvc
  labels:
    username: kjm24
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 1Gi
