---
apiVersion: v1
kind: Service
metadata:
  name: kjm24-test-redis-service
  labels:
    username: kjm24
    env: test
spec:
  type: ClusterIP
  selector:
    app: kjm24-test-redis
  ports:
  - name: kjm24-test-redis
    port: 6379
    targetPort: 6379
